version: '3.5'
services:
    vue-ui-admin:
        build:
            context: ./
            dockerfile: Dockerfile.dev
        ports:
        - "8081:8080"
        container_name: vue-ui-admin
        volumes:
        - ./:/usr/src/app
        - /usr/src/app/node_modules